apiVersion: v1
kind: "Service"
metadata:
  name: alertmanager-svc
  namespace: devops
  labels:
    name: alertmanager-svc
spec:
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: alertmanager
