apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: alertmanager
  name: alertmanager
  namespace: devops

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
#      annotations:
#        prometheus.io/port: '9090'
#        prometheus.io/scrape: 'true'
    spec:
      imagePullSecrets:
        - name: bycx-registry
      containers:
        - name: alertmanager
          imagePullPolicy: Always
          image: registry.boyait.9fwealth.com:1443/devops/images/alertmanager:0.15.1
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/data"
              name: data
            - mountPath: "/app/alertmanager.yml"
              name: alertmanager-config
              subPath: alertmanager.yml
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-nfs 
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
            - key: alertmanager.yml
              path: alertmanager.yml
