apiVersion: v1
kind: "Service"
metadata:
  name: grafana
  namespace: devops
  labels:
    name: grafana-service
spec:
  ports:
    - name: grafana-server
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana-server
