apiVersion: v1
kind: "Service"
metadata:
  name: prometheus
  namespace: devops
  labels:
    name: prometheus-service
spec:
  ports:
    - name: prometheus-server
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: prometheus-rest
      protocol: TCP
      port: 16010
      targetPort: 16010
  selector:
    app: prometheus-server
