apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-grafana-frontend
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    kubernetes.io/ingress.class: "nginx-port-80-443"
spec:
  rules:
  - host: prometheus.hd1pro.boyacx.com
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
        path: /
  - host: grafana.hd1pro.boyacx.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
  - host: alert.hd1pro.boyacx.com
    http:
      paths:
      - backend:
          serviceName: alertmanager-svc
          servicePort: 9093
        path: /
